/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example;
import org.example.Library;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Library library = new Library();
        if(library.someLibraryMethod() == true) {
            System.out.println("Success to import library");
        }
        System.out.println(new App().getGreeting());
    }
}
