services:
  mysql:
    image: mysql:latest  # 사용할 MySQL 이미지
    container_name: mysql-local  # 컨테이너 이름
    logging:
      driver: "json-file"
      options:
        max-size: "10m"         # 로그 파일 크기가 10MB를 넘으면 새로운 로그 파일로 교체
        max-file: "3"           # 최대 3개의 로그 파일을 보관 (log.1, log.2, log.3 등)
    environment:
      MYSQL_ROOT_PASSWORD: example  # root 사용자 비밀번호
      MYSQL_DATABASE: study  # 자동으로 생성할 데이터베이스
    ports:
      - "3306:3306"  # 외부 3306 포트를 MySQL 컨테이너의 3306 포트에 매핑
    volumes:
      - mysql-local:/var/lib/mysql  # 데이터 지속성을 위한 볼륨 설정

volumes:
  mysql-local:
    driver: local  # 로컬 드라이버를 사용하여 데이터 저장