groups:
  - name: alert_rules
    rules:
      - alert: MyAppContainerDown
        expr: (time() - container_last_seen{name="nginx-test"}) > 10
        for: 3s
        labels:
          severity: critical
        annotations:
          summary: "MyApp container down"
          description: "The Docker container for MyApp has not been seen for more than 1 minute."