
GET http://192.168.9.5:5601/api/status

###################################################
#####
#####  Check Data Exist
#####
###################################################
GET http://192.168.9.5:9200/docker-logs-*/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        { "match_phrase": { "agent.id.keyword": "4e7d7853-9dbe-4a8e-978c-8f587c948eab" } },
        { "match_phrase": { "fields.team": "developer" } }
      ]
    }
  },
  "size": 1
}

#-------------------------------------------------#

###################################################
#####
#####  Get Index Patterns
#####
###################################################

GET http://192.168.9.5:9200/.kibana/_search
Content-Type: application/json

{
  "query": {
    "term": {
      "type": {
        "value": "index-pattern"
      }
    }
  },
  "_source": ["index-pattern.title"]
}

#-------------------------------------------------#

###################################################
#####
#####  Delete Data of Index
#####
###################################################

DELETE http://192.168.9.5:9200/docker-logs-*

###

DELETE http://192.168.9.5:9200/filebeat-*
#-------------------------------------------------#

###################################################
#####
#####  Delete Data of Index with Condition
#####
###################################################

DELETE http://192.168.9.5:9200/.kibana/_doc/index-pattern:filebeat-*

###

DELETE http://192.168.9.5:9200/.kibana/_doc/index-pattern:579363e0-38e8-11ef-8b0e-2709331f4883

#-------------------------------------------------#
# index-pattern:6b411a40-3488-11ef-8b0e-2709331f4883
# index-pattern:filebeat-*
###################################################
#####
#####  Delete Index Pattern
#####
###################################################

POST http://192.168.9.5:9200/docker-logs-*/_delete_by_query
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        { "match_phrase": { "fields.id": "nitro-1" } }
      ]
    }
  }
}

#-------------------------------------------------#

###################################################
#####
#####  Get Shards Information of Index
#####
###################################################

GET http://192.168.9.5:9200/_cat/shards/docker-logs-*?v


#-------------------------------------------------#

###################################################
#####
#####  Get Shards Informations
#####
###################################################

GET http://192.168.9.5:9200/_cat/shards?v

#-------------------------------------------------#

###################################################
#####
#####  Elasticsearch 인덱스 템플릿 및 ILM 정책 설정
#####
###################################################

GET http://192.168.9.5:9200/_template/docker-logs-template
Content-Type: application/json

{
  "index_patterns": ["docker-logs-*"],
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "_source": {
      "enabled": true
    },
    "properties": {
      "@timestamp": {
        "type": "date"
      }
    }
  }
}

#-------------------------------------------------#

###################################################
#####
#####  ILM 정책 설정
#####
###################################################

PUT http://192.168.9.5:9200/_ilm/policy/docker-logs-ilm-policy
Content-Type: application/json

{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_size": "50gb",
            "max_age": "30d"
          }
        }
      },
      "delete": {
        "min_age": "90d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}


#-------------------------------------------------#

###################################################
#####
#####  ILM 정책 조회
#####
###################################################

GET http://192.168.9.5:9200/_ilm/policy

#-------------------------------------------------#

###################################################
#####
#####  특정 ILM 정책 조회
#####
###################################################


GET http://192.168.9.5:9200/_ilm/policy/policy_name

#-------------------------------------------------#

###################################################
#####
#####  Index 탬플릿 조회
#####
###################################################

GET http://192.168.9.5:9200/_template

#-------------------------------------------------#

###################################################
#####
##### 현재 생성된 모든 인덱
#####
###################################################

GET http://192.168.9.5:9200/_cat/indices?v


#-------------------------------------------------#

###################################################
#####
##### 인덱스 정보 조회
#####
###################################################

GET http://192.168.9.5:9200/docker-logs-2024.07.03/_settings

#-------------------------------------------------#

###################################################
#####
##### 인덱스 정보 조회 (index-pattern)
#####
###################################################

GET http://192.168.9.5:9200/docker-logs-*/_settings

###

GET http://192.168.9.5:9200/docker-logs-2024.07.03


###################################################
#####
##### ilm 등록
#####
###################################################

PUT http://192.168.9.5:9200/_ilm/policy/rollover-policy
Content-Type: application/json

{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_primary_shard_size": "50GB",
            "max_age": "30d"
          }
        }
      },
      "delete": {
        "min_age": "90d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}

### rollover-policy와 index 맵핑하기-1

PUT http://192.168.9.5:9200/_template/chain-error-template
Content-Type: application/json

{
  "index_patterns": ["chain-error-*"],
  "settings": {
    "index.lifecycle.name": "rollover-policy"
  }
}

### rollover-policy와 index 맵핑하기-2

PUT http://192.168.9.5:9200/_template/chain-template
Content-Type: application/json

{
  "index_patterns": ["chain-*"],
  "settings": {
    "index.lifecycle.name": "90-days-default"
  }
}

### template 확인(rollover-policy와 index 맵핑하기-1 결과)

GET http://192.168.9.5:9200/_template/chain-error-template


### template 확인(rollover-policy와 index 맵핑하기-2 결과)

GET http://192.168.9.5:9200/_template/chain-template


###################################################
#####
##### ingest pipeline 추가
#####
###################################################
PUT http://192.168.9.5:9200/_ingest/pipeline/extract_number
Content-Type: application/json

{
  "description": "Extract number from message",
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": ["number=%{NUMBER:number}"]
      }
    },
    {
      "convert": {
        "field": "number",
        "type": "long"
      }
    }
  ]
}

##################################################
#####
##### rollover aliases 확인
#####
###################################################
GET http://192.168.9.5:9200/_cat/aliases?v
