services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.11
    container_name: filebeat
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "3"
    user: root
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./.registry:/usr/share/filebeat/data/registry
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
    networks:
      - logclient
networks:
  logclient:
    driver: bridge
